"""empty message

Revision ID: 29ec83b63db8
Revises: a47f57782b04
Create Date: 2021-03-07 14:40:06.122123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ec83b63db8'
down_revision = 'a47f57782b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('premium_status', sa.String(length=50), nullable=True))
    op.drop_column('user', 'subscriptoin_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscriptoin_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'premium_status')
    # ### end Alembic commands ###
