"""empty message

Revision ID: 38aa99183fce
Revises: c961a87f246f
Create Date: 2021-03-07 13:29:53.944610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aa99183fce'
down_revision = 'c961a87f246f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
