"""empty message

Revision ID: 485449a7bcc1
Revises: 29ec83b63db8
Create Date: 2021-03-21 16:25:06.582822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485449a7bcc1'
down_revision = '29ec83b63db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('premium_subscription', sa.String(length=50), nullable=True))
    op.drop_column('user', 'premium_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('premium_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'premium_subscription')
    # ### end Alembic commands ###
