"""empty message

Revision ID: 489e4b197b80
Revises: 485449a7bcc1
Create Date: 2021-03-25 14:45:49.799739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489e4b197b80'
down_revision = '485449a7bcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_end')
    # ### end Alembic commands ###
