"""empty message

Revision ID: 61a849a808e0
Revises: ee813fccf165
Create Date: 2020-04-15 10:43:40.742638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a849a808e0'
down_revision = 'ee813fccf165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activity_is_running', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user', sa.Column('has_unsaved_activity_record', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_unsaved_activity_record')
    op.drop_column('user', 'activity_is_running')
    # ### end Alembic commands ###
