"""empty message

Revision ID: 6e65e12abef6
Revises: 4d48fca52aef
Create Date: 2021-03-07 13:55:45.660892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e65e12abef6'
down_revision = '4d48fca52aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'open_stripe_session', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'open_stripe_session', type_='unique')
    # ### end Alembic commands ###
