"""empty message

Revision ID: 7a482ce6dd27
Revises: 3593fb78bfd5
Create Date: 2020-04-15 10:31:58.436315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a482ce6dd27'
down_revision = '3593fb78bfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'name')
    op.drop_column('user', 'locale')
    op.drop_column('user', 'given_name')
    op.drop_column('user', 'picture')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'family_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('family_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('picture', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('given_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
