"""empty message

Revision ID: a47f57782b04
Revises: 6e65e12abef6
Create Date: 2021-03-07 14:38:24.362396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47f57782b04'
down_revision = '6e65e12abef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscriptoin_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscriptoin_status')
    # ### end Alembic commands ###
