"""empty message

Revision ID: dced1a36eac4
Revises: 59b07b07556e
Create Date: 2019-03-05 10:35:28.410529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dced1a36eac4'
down_revision = '59b07b07556e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activity', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'activity', type_='unique')
    # ### end Alembic commands ###
