"""empty message

Revision ID: 14f630714d2f
Revises: 93d765146bfc
Create Date: 2018-05-31 17:25:12.196493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14f630714d2f'
down_revision = '93d765146bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_current_activities', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.drop_column('users_current_activities', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_current_activities', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users_current_activities', 'started_at')
    # ### end Alembic commands ###
