"""empty message

Revision ID: 23a90db681ea
Revises: ab5d4126111c
Create Date: 2018-06-11 09:48:11.824525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23a90db681ea'
down_revision = 'ab5d4126111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('picture', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('given_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('family_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('credentials', sa.VARCHAR(length=7000), autoincrement=False, nullable=True),
    sa.Column('current_activity', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stopped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('id', name='user_id_key')
    )
    # ### end Alembic commands ###
