"""empty message

Revision ID: 51d2b3717c01
Revises: 6a5703c9b81a
Create Date: 2018-06-08 16:28:36.992720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51d2b3717c01'
down_revision = '6a5703c9b81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_activitiy')
    op.drop_table('credentials')
    op.add_column('user', sa.Column('credentials', sa.String(length=7000), nullable=False))
    op.add_column('user', sa.Column('current_activity', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('stopped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stopped_at')
    op.drop_column('user', 'started_at')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'current_activity')
    op.drop_column('user', 'credentials')
    op.create_table('credentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('credentials', sa.VARCHAR(length=7000), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='credentials_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credentials_pkey'),
    sa.UniqueConstraint('id', name='credentials_id_key')
    )
    op.create_table('current_activitiy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('stopped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='current_activitiy_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='current_activitiy_pkey')
    )
    # ### end Alembic commands ###
