"""empty message

Revision ID: 5a4c6b5e48da
Revises: 51d2b3717c01
Create Date: 2018-06-11 09:38:07.127102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a4c6b5e48da'
down_revision = '51d2b3717c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'credentials',
               existing_type=sa.VARCHAR(length=7000),
               nullable=True)
    op.alter_column('user', 'current_activity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'current_activity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'credentials',
               existing_type=sa.VARCHAR(length=7000),
               nullable=False)
    # ### end Alembic commands ###
