"""empty message

Revision ID: 6a5703c9b81a
Revises: e0e30eb5fcfd
Create Date: 2018-06-08 16:17:08.834416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a5703c9b81a'
down_revision = 'e0e30eb5fcfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_activitiy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('users_current_activities')
    op.create_unique_constraint(None, 'credentials', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'credentials', type_='unique')
    op.create_table('users_current_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stopped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_current_activities_pkey'),
    sa.UniqueConstraint('id', name='users_current_activities_id_key')
    )
    op.drop_table('current_activitiy')
    # ### end Alembic commands ###
