"""empty message

Revision ID: 93d765146bfc
Revises: 28ef5e7ada47
Create Date: 2018-05-31 17:20:07.095845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d765146bfc'
down_revision = '28ef5e7ada47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_current_activities', sa.Column('stopped_at', sa.DateTime(), nullable=True))
    op.drop_column('users_current_activities', 'stoped_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_current_activities', sa.Column('stoped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users_current_activities', 'stopped_at')
    # ### end Alembic commands ###
