"""empty message

Revision ID: fd703c7644a7
Revises: 5c87fb9cce50
Create Date: 2018-05-31 17:08:12.391619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd703c7644a7'
down_revision = '5c87fb9cce50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_current_activities', sa.Column('stoped_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'users_current_activities', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_current_activities', type_='unique')
    op.drop_column('users_current_activities', 'stoped_at')
    # ### end Alembic commands ###
